### ISSUE TITLE
Safari HistoryAgeInDaysLimit(s)

### ISSUE THREAD

**Issue by lafarer** [lafarer/ansible-role-osx-defaults#3]
Defined as `Safari_HistoryAgeInDaysLimits` (plural) in vars but referred to as `Safari_HistoryAgeInDaysLimit` (singular) in tasks.

**Comment by marcomc** [comment]
I think it's used in a with_subelements loop
As list of subelements that's why is referred as singular item

**Comment by marcomc** [comment]
Ah, no
It's two different bars

**Comment by marcomc** [comment]
Check in vars/main.yml

**Comment by marcomc** [comment]
![Uploading 91212485...]

**Comment by marcomc** [comment]
![image](https://user-images.githubusercontent.com/1428680/91212526-ba425f80-e6e6-11ea-8cda-c23162b32f12.jpeg)

**Comment by marcomc** [comment]
I confirm this is not a real issue
with the latest PR I am renaming HistoryAgeInDaysLimits into HistoryAgeInDaysLimit_Options to avoid confusion with HistoryAgeInDaysLimit (without 's') which are two distinct variables
